PLUGIN_NAME=		if-clients-widget
PLUGIN_VERSION=		0.1
PLUGIN_DEPENDS=		if-clients-widget
PLUGIN_COMMENT=		Widget for the quick view of the connected devices
PLUGIN_MAINTAINER=	m3e-g

.include "../../Mk/plugins.mk"
